### ISSUE TITLE
太冷清了， 发个issue

### ISSUE THREAD

**Issue by wenzi0github** [wenzi0github/utils#1]
there has some javascript utils, we want to help you.

**Comment by wenzi0github** [comment]
npmjs: https://www.npmjs.com/package/gh-qqnews-utils

**Comment by wenzi0github** [comment]
how to extend axios, add jsonp, but I need all axios functions

**Comment by wenzi0github** [comment]
hava done, please link to https://www.npmjs.com/package/gh-qqnews-hunger

**Comment by jdz321** [comment]
啊   小姐姐啊能不能加个微信。。。   前同事0.0

**Comment by wenzi0github** [comment]
> how to extend axios, add jsonp, but I need all axios functions

方向错了，实现起来就很费劲，其实从一开始就不应该在axios外面包一层，而是直接扩展adapter，就好很多。
